/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sdgp.dashboardFrames;

import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author alao_
 */
public class BarPanelNew extends javax.swing.JInternalFrame {

    /**
     * Creates new form BarPanelNew
     */
    public BarPanelNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("VIEW CHART");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setText("Number Of Companies In Projects");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(291, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         DefaultCategoryDataset data = new DefaultCategoryDataset();
      
        data.setValue(13,"ProjectAcroynm","SMR");
        data.setValue(18,"ProjectAcroynm","EUROcirCol");
        data.setValue(10,"ProjectAcroynm","Darwin");
        data.setValue(15,"ProjectAcroynm","MetaRNA");
        data.setValue(12,"ProjectAcroynm","BACI");
        data.setValue(37,"ProjectAcroynm","BiodivERsA3");
        data.setValue(8,"ProjectAcroynm","EDEN");
        data.setValue(15,"ProjectAcroynm","BIG loT");
        data.setValue(1,"ProjectAcroynm","CatHet");
        data.setValue(15,"ProjectAcroynm","EpiPredict");
        data.setValue(9,"ProjectAcroynm","ThermoDrill");
        data.setValue(3,"ProjectAcroynm","MaXIMA");
        data.setValue(9,"ProjectAcroynm","socSMCs");
        data.setValue(36,"ProjectAcroynm","CARTRE");
        data.setValue(11,"ProjectAcroynm","FLEDGED");
        data.setValue(12,"ProjectAcroynm","optiTRUCK");
        data.setValue(26,"ProjectAcroynm","FIThydro");
        data.setValue(12,"ProjectAcroynm","E2mC");
        data.setValue(1,"ProjectAcroynm","PAPTIC");
        data.setValue(11,"ProjectAcroynm","RE-SERVE");
        data.setValue(6,"ProjectAcroynm","GATES");
        data.setValue(49,"ProjectAcroynm","INTAROS");
        data.setValue(74,"ProjectAcroynm","ENABLE-S3");
        data.setValue(11,"ProjectAcroynm","MOBISTYLE");
        data.setValue(11,"ProjectAcroynm","AgroCylce");
        data.setValue(9,"ProjectAcroynm","Factory2Fit");
        data.setValue(9,"ProjectAcroynm","INNOLABS");
        data.setValue(17,"ProjectAcroynm","MH-MD");
        data.setValue(1,"ProjectAcroynm","CALC");
        data.setValue(6,"ProjectAcroynm","ATTRACkTIVE");
        data.setValue(27,"ProjectAcroynm","Prosperity");
        data.setValue(18,"ProjectAcroynm","SlideWiki");
        data.setValue(13,"ProjectAcroynm","ATENA");
        data.setValue(1,"ProjectAcroynm","MARS");
        data.setValue(8,"ProjectAcroynm","PERCEIVE");
        data.setValue(25,"ProjectAcroynm","POnTE");
        data.setValue(8,"ProjectAcroynm","Cell3Ditor");
        data.setValue(38,"ProjectAcroynm","SemI40");
        data.setValue(1,"ProjectAcroynm","INTHER");
        data.setValue(21,"ProjectAcroynm","I-REACT");
        data.setValue(10,"ProjectAcroynm","MAVEN");
        data.setValue(19,"ProjectAcroynm","Waste4Think");
        data.setValue(8,"ProjectAcroynm","SUMMA");
        data.setValue(1,"ProjectAcroynm","StemHealth");
        data.setValue(1,"ProjectAcroynm","SOLCRIMET");
        data.setValue(20,"ProjectAcroynm","PROTON");
        data.setValue(2,"ProjectAcroynm","OBEDIA-MARK");
        data.setValue(1,"ProjectAcroynm","SYSDYNET");
        data.setValue(28,"ProjectAcroynm","UrBAN-WASTE");
        data.setValue(35,"ProjectAcroynm","ANYWHERE");
        data.setValue(5,"ProjectAcroynm","TankRob");
        data.setValue(1,"ProjectAcroynm","SmartCast");
        data.setValue(1,"ProjectAcroynm","MPIPETrace");
        data.setValue(50,"ProjectAcroynm","ERA4CS");
        data.setValue(1,"ProjectAcroynm","Bug-Flash");
        data.setValue(2,"ProjectAcroynm","nuDirections");
        data.setValue(15,"ProjectAcroynm","DORA");
        data.setValue(10,"ProjectAcroynm","PRODIAS");
        data.setValue(25,"ProjectAcroynm","TREASURE");
        data.setValue(1,"ProjectAcroynm","Light4Sight");
        data.setValue(16,"ProjectAcroynm","MINOUW");
        data.setValue(1,"ProjectAcroynm","ISIFit");
        data.setValue(31,"ProjectAcroynm","Strength2Food");
        data.setValue(18,"ProjectAcroynm","BRODGERS");
        data.setValue(11,"ProjectAcroynm","DIAGORAS");
        data.setValue(18,"ProjectAcroynm","PROSPECT");
        data.setValue(27,"ProjectAcroynm","FINESSE");
        data.setValue(13,"ProjectAcroynm","Icare");
        data.setValue(25,"ProjectAcroynm","iSQAPER");
        
        JFreeChart jChart = ChartFactory.createBarChart("Number Of Companies In Project","ProjectAcronym", "Number Of Companies", data, PlotOrientation.VERTICAL,true, true, false);
        
        CategoryPlot plot = jChart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.BLACK);
        
        ChartPanel chartFrm = new ChartPanel(jChart);
        
        //ChartFrame chartFrm = new ChartFrame("Number Of Companies In Project",jChart,true);
        jPanel1.add(chartFrm);
        chartFrm.setVisible(true);
        chartFrm.setSize(760,351);
        
        CategoryAxis domainAxis = jChart.getCategoryPlot().getDomainAxis();
        domainAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_90);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
