/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sdgp;

import sdgp.dashboardFrames.BarPanelNew;
import sdgp.dashboardFrames.LineGraph;
import sdgp.dashboardFrames.PieChart;

/**
 *
 * @author MD
 */
public class UserDashboard extends javax.swing.JFrame {
    private String userEmail;
    private String userName;

    /**
     * Creates new form PieChartDashboard
     */
    public UserDashboard(String userEmail, String userName) {
        initComponents();
        this.userEmail = userEmail;
        this.userName = userName;
        usernameDisplay.setText("Welcome, "+ userName + ". ("+ userEmail +")");
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();
        menuFrames = new javax.swing.JMenu();
        menuFrame1 = new javax.swing.JMenuItem();
        menuFrame2 = new javax.swing.JMenuItem();
        menuFrame3 = new javax.swing.JMenuItem();
        usernameDisplay = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 839, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        menuFile.setText("File");

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuFile.add(menuLogout);

        jMenuBar1.add(menuFile);

        menuFrames.setText("Frames");

        menuFrame1.setText("Pie Chart");
        menuFrame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFrame1ActionPerformed(evt);
            }
        });
        menuFrames.add(menuFrame1);

        menuFrame2.setText("Bar Chart");
        menuFrame2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFrame2ActionPerformed(evt);
            }
        });
        menuFrames.add(menuFrame2);

        menuFrame3.setText("Line Graph");
        menuFrame3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFrame3ActionPerformed(evt);
            }
        });
        menuFrames.add(menuFrame3);

        jMenuBar1.add(menuFrames);

        usernameDisplay.setText("Welcome,");
        jMenuBar1.add(usernameDisplay);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        this.dispose();
        Welcome_Page w = new Welcome_Page();
        w.setVisible(true);
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuFrame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFrame1ActionPerformed
        PieChart f = new PieChart();
        desktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_menuFrame1ActionPerformed

    private void menuFrame2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFrame2ActionPerformed
        BarPanelNew f = new BarPanelNew();
        desktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_menuFrame2ActionPerformed

    private void menuFrame3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFrame3ActionPerformed
        // TODO add your handling code here:
        LineGraph f = new LineGraph();
        //desktop.add(f);
        //f.setVisible(true);
    }//GEN-LAST:event_menuFrame3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UserDashboard().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuFrame1;
    private javax.swing.JMenuItem menuFrame2;
    private javax.swing.JMenuItem menuFrame3;
    private javax.swing.JMenu menuFrames;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenu usernameDisplay;
    // End of variables declaration//GEN-END:variables
}
