/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
*commit test
 */
package sdgp;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author lelouch
 */
public class Welcome_Page extends javax.swing.JFrame {
    private static Statement st;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    

    /**
     * Creates new form Login1
     */
    public Welcome_Page() {
        initComponents();
        conn = db.users_db();
        
        jPanel1.setFocusable(true);
        this.userNameIcon.setVisible(false);
        this.userNameTextField.setVisible(false);
        this.registerTitleLabel.setVisible(false);
        this.emailIconLabel.setVisible(false);
        this.registerBtnLabel.setVisible(false);
        this.registerBtn.setVisible(false);
        this.emailAddress.setVisible(false);
        this.passwordIconLabel2.setVisible(false);
        this.typeOfUser.setVisible(false);
        this.typeOfUserComboBox.setVisible(false);
        this.emailTextField.setVisible(false);
        this.passwordTextField.setVisible(false);
        this.confirmPasswordTextField.setVisible(false);
        this.passwordPlaceHolder2.setVisible(false);
        this.passwordPlaceHolder3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userNameTextField = new javax.swing.JTextField();
        userNameIcon = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordPlaceHolder2 = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        passwordPlaceHolder3 = new javax.swing.JTextField();
        confirmPasswordTextField = new javax.swing.JPasswordField();
        typeOfUser = new javax.swing.JLabel();
        typeOfUserComboBox = new javax.swing.JComboBox<>();
        emailAddress = new javax.swing.JSeparator();
        registerTitleLabel = new javax.swing.JLabel();
        passwordIconLabel2 = new javax.swing.JLabel();
        emailIconLabel = new javax.swing.JLabel();
        registerBtn = new javax.swing.JPanel();
        registerBtnLabel = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        userEmailTextField = new javax.swing.JTextField();
        passwordPlaceHolder1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        userIconLabel = new javax.swing.JLabel();
        signInBtn = new javax.swing.JPanel();
        signinBtnLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        signInTitleLabel = new javax.swing.JLabel();
        passwordIconLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        selectUser = new javax.swing.JLabel();
        selectUserComboBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        signIn = new javax.swing.JPanel();
        signInLabel = new javax.swing.JLabel();
        register = new javax.swing.JPanel();
        registerLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameTextField.setBackground(new java.awt.Color(51, 51, 51));
        userNameTextField.setForeground(new java.awt.Color(204, 204, 204));
        userNameTextField.setText("Your name...");
        userNameTextField.setBorder(null);
        userNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameTextFieldFocusLost(evt);
            }
        });
        jPanel1.add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 120, 40));

        userNameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sdgp/Icons/user.png"))); // NOI18N
        jPanel1.add(userNameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, 40));

        emailTextField.setBackground(new java.awt.Color(51, 51, 51));
        emailTextField.setForeground(new java.awt.Color(204, 204, 204));
        emailTextField.setText("Your Email...");
        emailTextField.setBorder(null);
        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusLost(evt);
            }
        });
        jPanel1.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 260, 40));

        passwordPlaceHolder2.setBackground(new java.awt.Color(51, 51, 51));
        passwordPlaceHolder2.setForeground(new java.awt.Color(204, 204, 204));
        passwordPlaceHolder2.setText("Your Password...");
        passwordPlaceHolder2.setBorder(null);
        passwordPlaceHolder2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordPlaceHolder2FocusGained(evt);
            }
        });
        jPanel1.add(passwordPlaceHolder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 260, 40));

        passwordTextField.setBackground(new java.awt.Color(51, 51, 51));
        passwordTextField.setForeground(new java.awt.Color(255, 255, 255));
        passwordTextField.setBorder(null);
        passwordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTextFieldFocusLost(evt);
            }
        });
        jPanel1.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 260, 40));

        passwordPlaceHolder3.setBackground(new java.awt.Color(51, 51, 51));
        passwordPlaceHolder3.setForeground(new java.awt.Color(204, 204, 204));
        passwordPlaceHolder3.setText("Confirm Password...");
        passwordPlaceHolder3.setBorder(null);
        passwordPlaceHolder3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordPlaceHolder3FocusGained(evt);
            }
        });
        jPanel1.add(passwordPlaceHolder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 260, 40));

        confirmPasswordTextField.setBackground(new java.awt.Color(51, 51, 51));
        confirmPasswordTextField.setForeground(new java.awt.Color(255, 255, 255));
        confirmPasswordTextField.setBorder(null);
        confirmPasswordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPasswordTextFieldFocusLost(evt);
            }
        });
        jPanel1.add(confirmPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 260, 40));

        typeOfUser.setForeground(new java.awt.Color(255, 255, 255));
        typeOfUser.setText("Type of user:");
        jPanel1.add(typeOfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, 20));

        typeOfUserComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Administrator" }));
        typeOfUserComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeOfUserComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(typeOfUserComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, -1, -1));

        emailAddress.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(emailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 270, 20));

        registerTitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        registerTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerTitleLabel.setText("Register");
        jPanel1.add(registerTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 140, 40));

        passwordIconLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sdgp/Icons/password.png"))); // NOI18N
        jPanel1.add(passwordIconLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, 40));

        emailIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sdgp/Icons/Email.png"))); // NOI18N
        jPanel1.add(emailIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        registerBtn.setBackground(new java.awt.Color(51, 51, 51));
        registerBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        registerBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerBtnLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        registerBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerBtnLabel.setText("              Register");
        registerBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerBtnLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                registerBtnLabelMouseReleased(evt);
            }
        });
        registerBtn.add(registerBtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 5, 240, 40));

        jPanel1.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 250, 50));

        loginPanel.setBackground(new java.awt.Color(51, 51, 51));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        loginPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 140, 10));

        userEmailTextField.setBackground(new java.awt.Color(51, 51, 51));
        userEmailTextField.setForeground(new java.awt.Color(204, 204, 204));
        userEmailTextField.setText("Your Email...");
        userEmailTextField.setBorder(null);
        userEmailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userEmailTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userEmailTextFieldFocusLost(evt);
            }
        });
        loginPanel.add(userEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 260, 40));

        passwordPlaceHolder1.setBackground(new java.awt.Color(51, 51, 51));
        passwordPlaceHolder1.setForeground(new java.awt.Color(204, 204, 204));
        passwordPlaceHolder1.setText("Your Password...");
        passwordPlaceHolder1.setBorder(null);
        passwordPlaceHolder1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordPlaceHolder1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordPlaceHolder1FocusLost(evt);
            }
        });
        loginPanel.add(passwordPlaceHolder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 260, 40));

        jPasswordField1.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setToolTipText("");
        jPasswordField1.setBorder(null);
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        loginPanel.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 260, 40));

        userIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sdgp/Icons/user.png"))); // NOI18N
        loginPanel.add(userIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        signInBtn.setBackground(new java.awt.Color(51, 51, 51));
        signInBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        signInBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signinBtnLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        signinBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        signinBtnLabel.setText("              Sign in");
        signinBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signinBtnLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signinBtnLabelMouseReleased(evt);
            }
        });
        signInBtn.add(signinBtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 5, 240, 40));

        loginPanel.add(signInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 250, 50));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        loginPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 270, 20));

        signInTitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        signInTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        signInTitleLabel.setText("Sign in");
        loginPanel.add(signInTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        passwordIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sdgp/Icons/password.png"))); // NOI18N
        loginPanel.add(passwordIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 40, 40));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        loginPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 270, 20));

        selectUser.setForeground(new java.awt.Color(255, 255, 255));
        selectUser.setText("Type of user:");
        loginPanel.add(selectUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        selectUserComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Administrator" }));
        selectUserComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectUserComboBoxActionPerformed(evt);
            }
        });
        loginPanel.add(selectUserComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jPanel1.add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 400));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signIn.setBackground(new java.awt.Color(51, 51, 51));
        signIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signInMousePressed(evt);
            }
        });

        signInLabel.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        signInLabel.setForeground(new java.awt.Color(255, 255, 255));
        signInLabel.setText("     Sign In");
        signInLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signInLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signInLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout signInLayout = new javax.swing.GroupLayout(signIn);
        signIn.setLayout(signInLayout);
        signInLayout.setHorizontalGroup(
            signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        signInLayout.setVerticalGroup(
            signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signInLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.add(signIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 110, 40));

        register.setBackground(new java.awt.Color(51, 51, 51));

        registerLabel.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerLabel.setText("    Register");
        registerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                registerLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout registerLayout = new javax.swing.GroupLayout(register);
        register.setLayout(registerLayout);
        registerLayout.setHorizontalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        registerLayout.setVerticalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sdgp/EU_Flag.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 580));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMousePressed
        resetSignInFields();
    }//GEN-LAST:event_registerLabelMousePressed

    private void signInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_signInMousePressed

    private void signInLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInLabelMousePressed
        resetRegisterFields();
  
    }//GEN-LAST:event_signInLabelMousePressed

    private void typeOfUserComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeOfUserComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeOfUserComboBoxActionPerformed

    private void selectUserComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectUserComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectUserComboBoxActionPerformed

    private void userEmailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userEmailTextFieldFocusGained
        // TODO add your handling code here:
        if(userEmailTextField.getText().equals("Your Email...")){
            userEmailTextField.setText("");
        }
        
        userEmailTextField.setForeground(Color.WHITE);
    }//GEN-LAST:event_userEmailTextFieldFocusGained

    private void userEmailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userEmailTextFieldFocusLost
        // TODO add your handling code here:
        if(userEmailTextField.getText().equals("")){
            userEmailTextField.setText("Your Email...");
        }
        
        userEmailTextField.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_userEmailTextFieldFocusLost

    private void passwordPlaceHolder1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordPlaceHolder1FocusGained
        // TODO add your handling code here:
        if(passwordPlaceHolder1.getText().equals("Your Password...")){
            passwordPlaceHolder1.setVisible(false);
            jPasswordField1.requestFocus();
            
        }
        
    }//GEN-LAST:event_passwordPlaceHolder1FocusGained

    private void passwordPlaceHolder1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordPlaceHolder1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPlaceHolder1FocusLost

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
        if(jPasswordField1.getText().equals("")){
            passwordPlaceHolder1.setVisible(true);
            
        }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void emailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusGained
        // TODO add your handling code here:
        if(this.emailTextField.getText().equals("Your Email...")){
            this.emailTextField.setText("");
        }
        
        this.emailTextField.setForeground(Color.WHITE);
    }//GEN-LAST:event_emailTextFieldFocusGained

    private void emailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusLost
        // TODO add your handling code here:
        if(this.emailTextField.getText().equals("")){
            this.emailTextField.setText("Your Email...");
        }
        this.emailTextField.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_emailTextFieldFocusLost

    private void passwordPlaceHolder2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordPlaceHolder2FocusGained
        // TODO add your handling code here:
        if(this.passwordPlaceHolder2.getText().equals("Your Password...")){
            this.passwordPlaceHolder2.setVisible(false);
            this.passwordTextField.requestFocus();
            
        }
    }//GEN-LAST:event_passwordPlaceHolder2FocusGained

    private void passwordPlaceHolder3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordPlaceHolder3FocusGained
        // TODO add your handling code here:
        if(this.passwordPlaceHolder3.getText().equals("Confirm Password...")){
            this.passwordPlaceHolder3.setVisible(false);
            this.confirmPasswordTextField.requestFocus();
            
        }
    }//GEN-LAST:event_passwordPlaceHolder3FocusGained

    private void passwordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextFieldFocusLost
        // TODO add your handling code here:
        if(passwordTextField.getText().equals("")){
            this.passwordPlaceHolder2.setVisible(true);
        }
    }//GEN-LAST:event_passwordTextFieldFocusLost

    private void confirmPasswordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordTextFieldFocusLost
        // TODO add your handling code here:
        if(confirmPasswordTextField.getText().equals("")){
            this.passwordPlaceHolder3.setVisible(true);
        }
    }//GEN-LAST:event_confirmPasswordTextFieldFocusLost

    private void signInLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInLabelMouseReleased
        // TODO add your handling code here:
        int p = this.loginPanel.getX();
        if(p>-1){
            Animacion.Animacion.mover_izquierda(510,117,2,3,loginPanel);
        }
        signinBtnLabel.setVisible(true);
        signInBtn.setVisible(true);
        signInTitleLabel.setVisible(true);
        userIconLabel.setVisible(true);
        userEmailTextField.setVisible(true);
        jPasswordField1.setVisible(true);
        selectUser.setVisible(true);
        passwordPlaceHolder1.setVisible(true);
        selectUserComboBox.setVisible(true);
        this.userNameIcon.setVisible(false);
        this.userNameTextField.setVisible(false);
        this.registerTitleLabel.setVisible(false);
        this.emailIconLabel.setVisible(false);
        this.registerBtnLabel.setVisible(false);
        this.registerBtn.setVisible(false);
        this.emailAddress.setVisible(false);
        this.passwordIconLabel2.setVisible(false);
        this.typeOfUser.setVisible(false);
        this.typeOfUserComboBox.setVisible(false);
        this.emailTextField.setVisible(false);
        this.passwordTextField.setVisible(false);
        this.confirmPasswordTextField.setVisible(false);
        this.passwordPlaceHolder2.setVisible(false);
        this.passwordPlaceHolder3.setVisible(false);
    }//GEN-LAST:event_signInLabelMouseReleased

    private void registerLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMouseReleased
        // TODO add your handling code here:
        int p = this.loginPanel.getX();
        if(p>-1){
            Animacion.Animacion.mover_derecha(117,510,2,3,loginPanel);
        }
        signinBtnLabel.setVisible(false);
        signInBtn.setVisible(false);
        signInTitleLabel.setVisible(false);
        userIconLabel.setVisible(false);
        selectUser.setVisible(false);
        userEmailTextField.setVisible(false);
        passwordPlaceHolder1.setVisible(false);
        jPasswordField1.setVisible(false);
        selectUserComboBox.setVisible(false);
        this.userNameIcon.setVisible(true);
        this.userNameTextField.setVisible(true);
        this.registerTitleLabel.setVisible(true);
        this.emailIconLabel.setVisible(true);
        this.registerBtnLabel.setVisible(true);
        this.registerBtn.setVisible(true);
        this.emailAddress.setVisible(true);
        this.passwordIconLabel2.setVisible(true);
        this.typeOfUser.setVisible(true);
        this.typeOfUserComboBox.setVisible(true);
        this.emailTextField.setVisible(true);
        this.passwordTextField.setVisible(true);
        this.confirmPasswordTextField.setVisible(true);
        this.passwordPlaceHolder2.setVisible(true);
        this.passwordPlaceHolder3.setVisible(true);
        
    }//GEN-LAST:event_registerLabelMouseReleased

    private void signinBtnLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinBtnLabelMousePressed
        // TODO add your handling code here:
        signInBtn.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_signinBtnLabelMousePressed

    private void signinBtnLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinBtnLabelMouseReleased
        // TODO add your handling code here:
        signInBtn.setBackground(new Color(51,51,51));
        String userName="";
        if(userEmailTextField.getText().equals("") ||  jPasswordField1.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill in all the fields");
            
        }else{
            

            try {
                String type = selectUserComboBox.getSelectedItem().toString();
                String sql = "";
                if(type.equals("User")){
                    try {
                        sql = "SELECT userName,userEmail, userPassword FROM Users where (userEmail =? and userPassword =?)";
                        pst = conn.prepareStatement(sql);
                        pst.setString(1,userEmailTextField.getText());
                        pst.setString(2,jPasswordField1.getText());
                        rs = pst.executeQuery();
                        userName = rs.getString("userName");
                    } catch (SQLException ex) {
                        Logger.getLogger(Welcome_Page.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }else{
                    try {
                        sql = "SELECT adminName, adminEmail, adminPassword FROM Admin where (adminEmail =? and adminPassword =?)";
                        pst = conn.prepareStatement(sql);
                        pst.setString(1,userEmailTextField.getText());
                        pst.setString(2,jPasswordField1.getText());
                        rs = pst.executeQuery();
                        userName = rs.getString("adminName");
                    } catch (SQLException ex) {
                        Logger.getLogger(Welcome_Page.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    
                }
                int count = 0;
                
                while(rs.next()){
                    count = count + 1;
                }
                String access = (type);
                if(access == "Administrator"){
                    if(count == 1){
                        
                        JOptionPane.showMessageDialog(null, "Login Successfull");
                        Admin a = new Admin(userEmailTextField.getText(),userName);
                        a.setVisible(true);
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null,"Your Email or Password that you entered are wrong!");
                        resetSignInFields();
                    }
                    
                }else{
                    if(count == 1){
                        
                        JOptionPane.showMessageDialog(null, "Login Successfull");
                        UserDashboard a = new UserDashboard(userEmailTextField.getText(),userName);
                        a.setVisible(true);
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null,"Your Email or Password you entered are wrong!");
                        resetSignInFields();
                    }
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(Welcome_Page.class.getName()).log(Level.SEVERE, null, ex);
            }
            

            

            
        }
        
    }//GEN-LAST:event_signinBtnLabelMouseReleased

    private void registerBtnLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnLabelMouseReleased
        // TODO add your handling code here:
        this.registerBtn.setBackground(new Color(51,51,51));
        
        if(registerFormValidation() == false && registerEmailValidation() == false && registerPasswordValidation() == false){
            String querry = "";
            if(typeOfUserComboBox.getSelectedItem().toString().equals("User")){
                try {
                    querry = "INSERT INTO Users (userName,userEmail,userPassword) VALUES(?,?,?)";
                    
                    pst = conn.prepareStatement(querry);
                    pst.setString(1,this.userNameTextField.getText());
                    pst.setString(2,this.emailTextField.getText());
                    pst.setString(3,this.passwordTextField.getText());
                    
                    pst.execute();
                    JOptionPane.showMessageDialog(null,"Successful, Thank you for registering");
                    resetRegisterFields();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Email Already Exists, please try again");
                        resetRegisterFields();
                        Logger.getLogger(Welcome_Page.class.getName()).log(Level.SEVERE, null, ex);
                }
                finally{
                try{
                    pst.close();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);


                }
            }
            }else{
                try {
                    querry = "INSERT INTO Admin (adminName, adminEmail, adminPassword) VALUES(?,?,?) ";
                    
                    pst = conn.prepareStatement(querry);
                    pst.setString(1,this.userNameTextField.getText());
                    pst.setString(2,this.emailTextField.getText());
                    pst.setString(3,this.passwordTextField.getText());
                    
                    
                    pst.execute();
                    JOptionPane.showMessageDialog(null,"Successful, Thank you for registering");
                    resetRegisterFields();
                        
                    }catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Email Already Exists, please try again");
                        resetRegisterFields();
                        Logger.getLogger(Welcome_Page.class.getName()).log(Level.SEVERE, null, ex);
                    }
                finally{
                try{
                    pst.close();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);


                }
            }
                }
            
            
            }
        
        
            
            
            
        
    }//GEN-LAST:event_registerBtnLabelMouseReleased

    private void userNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTextFieldFocusGained
        // TODO add your handling code here:
         if(this.userNameTextField.getText().equals("Your name...")){
            this.userNameTextField.setText("");
        }
        
        this.userNameTextField.setForeground(Color.WHITE);
    }//GEN-LAST:event_userNameTextFieldFocusGained

    private void userNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTextFieldFocusLost
        // TODO add your handling code here:
        if(this.userNameTextField.getText().equals("")){
            this.userNameTextField.setText("Your name...");
        }
        this.userNameTextField.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_userNameTextFieldFocusLost

    private void registerBtnLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnLabelMousePressed
        // TODO add your handling code here:
        this.registerBtn.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_registerBtnLabelMousePressed

    private void resetRegisterFields(){
        this.userNameTextField.setText("Your name...");
        this.emailTextField.setText("Your Email...");
        this.passwordTextField.setText("");
        this.confirmPasswordTextField.setText("");
        this.userNameTextField.requestFocus();
        this.emailTextField.requestFocus();
        this.passwordTextField.requestFocus();
        this.confirmPasswordTextField.requestFocus();
        this.userNameTextField.requestFocus();
    }
    
    private void resetSignInFields(){
        userEmailTextField.setText("Your Email...");
        jPasswordField1.setText("");
        userEmailTextField.requestFocus();
        jPasswordField1.requestFocus();
        userEmailTextField.requestFocus();
    }
    
    private boolean registerFormValidation(){
        boolean emptyFields = false;
        if(this.userNameTextField.getText().equals("") || this.emailTextField.getText().equals("") || this.passwordTextField.getText().equals("") || this.confirmPasswordTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill in all the fields");
            
            emptyFields = true;
        }else{
            emptyFields = false;
            
        }
        
        return emptyFields;
        
        
    }
    
    private boolean registerEmailValidation(){
        boolean error = false;
        String email = this.emailTextField.getText();
        if (!(Pattern.matches("^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$", email))){
                JOptionPane.showMessageDialog(null, "Please enter a valid email");
                this.emailTextField.setText("");
                this.emailTextField.requestFocus();
                error = true;
        }else{
            error = false;
        }
             
        return error;
    }
   
    
    private boolean registerPasswordValidation(){
        boolean match;
        if(!this.passwordTextField.getText().equals(this.confirmPasswordTextField.getText())){
                JOptionPane.showMessageDialog(null,"Passwords Not match, please try again.");
                this.passwordTextField.setText("");
                this.confirmPasswordTextField.setText("");
                this.confirmPasswordTextField.requestFocus();
                this.passwordTextField.requestFocus();
                        
                 match = true;
        }else{
            match = false;
        }
        return match;
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome_Page().setVisible(true);
            }
        });

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPasswordTextField;
    private javax.swing.JSeparator emailAddress;
    private javax.swing.JLabel emailIconLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel passwordIconLabel;
    private javax.swing.JLabel passwordIconLabel2;
    private javax.swing.JTextField passwordPlaceHolder1;
    private javax.swing.JTextField passwordPlaceHolder2;
    private javax.swing.JTextField passwordPlaceHolder3;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JPanel register;
    private javax.swing.JPanel registerBtn;
    private javax.swing.JLabel registerBtnLabel;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JLabel registerTitleLabel;
    private javax.swing.JLabel selectUser;
    private javax.swing.JComboBox<String> selectUserComboBox;
    private javax.swing.JPanel signIn;
    private javax.swing.JPanel signInBtn;
    private javax.swing.JLabel signInLabel;
    private javax.swing.JLabel signInTitleLabel;
    private javax.swing.JLabel signinBtnLabel;
    private javax.swing.JLabel typeOfUser;
    private javax.swing.JComboBox<String> typeOfUserComboBox;
    private javax.swing.JTextField userEmailTextField;
    private javax.swing.JLabel userIconLabel;
    private javax.swing.JLabel userNameIcon;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
