/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sdgp.PCFrames.PCPanels;

import java.awt.BorderLayout;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.jdbc.JDBCCategoryDataset;
import sdgp.db;

/**
 *
 * @author MD
 */
public class Panel1 extends javax.swing.JPanel {
    private static Statement st;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    DefaultListModel defaultListModel = new DefaultListModel();

    /**
     * Creates new form Panel2
     */
    private String contribCountry;
    private String selection;

    //Changes selected text for access in second panel
    
    public Panel1() {
        initComponents();
        conn = db.EU_data();
        this.bindData();
    }
    
    public String getCountry(){
        return this.selection;
    }
    
    public void setCountry(String choice){
        this.selection = choice;
    }
    
    private ArrayList getCountries() {
        ArrayList countries = new ArrayList();
        try {
            String sql = "SELECT country, count(*) as frequency FROM DataSet GROUP BY country ORDER BY count(*)desc";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                String country = rs.getString("country");
                countries.add(country);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Panel1.class.getName()).log(Level.SEVERE, null, ex);
        }

        return countries;
    }
    
    // Bind data to jList
    
    private void bindData() {
        getCountries().stream().forEach((country) -> {
            defaultListModel.addElement(country);
        });
        CountriesList.setModel(defaultListModel);
        CountriesList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        PieChartPanel = new javax.swing.JPanel();
        PCDisplay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CountriesList = new javax.swing.JList<>();
        CntryListLabel = new javax.swing.JLabel();
        PCPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(102, 255, 204));
        setPreferredSize(new java.awt.Dimension(715, 363));

        title.setText("Contributors classified by country");

        PCDisplay.setText("Display Pie Chart");
        PCDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCDisplayActionPerformed(evt);
            }
        });

        CountriesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        CountriesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CountriesListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CountriesList);

        CntryListLabel.setText("To refine search please choose a country from the list below");

        javax.swing.GroupLayout PCPanelLayout = new javax.swing.GroupLayout(PCPanel);
        PCPanel.setLayout(PCPanelLayout);
        PCPanelLayout.setHorizontalGroup(
            PCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        PCPanelLayout.setVerticalGroup(
            PCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PieChartPanelLayout = new javax.swing.GroupLayout(PieChartPanel);
        PieChartPanel.setLayout(PieChartPanelLayout);
        PieChartPanelLayout.setHorizontalGroup(
            PieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PieChartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PCDisplay)
                    .addComponent(PCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CntryListLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PieChartPanelLayout.setVerticalGroup(
            PieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PieChartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PCDisplay)
                    .addComponent(CntryListLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addGroup(PieChartPanelLayout.createSequentialGroup()
                        .addComponent(PCPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PieChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PieChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PCDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCDisplayActionPerformed
        
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        
        try {
            String sql = "SELECT country, count(*) as frequency FROM DataSet GROUP BY country ORDER BY count(*)desc";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                String country = rs.getString("country");
                String frequency = rs.getString("frequency");
                pieDataset.setValue(country, Integer.parseInt(frequency));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Panel1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        /**
        pieDataset.setValue("One", new Integer(10));
        pieDataset.setValue("Two", new Integer(20));
        pieDataset.setValue("Three", new Integer(30));
        pieDataset.setValue("Four", new Integer(10));
        pieDataset.setValue("Five", new Integer(20));
        pieDataset.setValue("Six", new Integer(10));
        **/
        
        JFreeChart chart = ChartFactory.createPieChart("Contributors based on Location", pieDataset, true, true, true);
        PiePlot p  = (PiePlot)chart.getPlot();
        ChartPanel panel = new ChartPanel(chart);
        PCPanel.add(panel);
        panel.setVisible(true);
        panel.setSize(376,270);
        
    }//GEN-LAST:event_PCDisplayActionPerformed

    private void CountriesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CountriesListMouseClicked
        // TODO add your handling code here:
        setCountry(CountriesList.getSelectedValue());
        Component rootPane = null;
        JOptionPane.showMessageDialog(rootPane, CountriesList.getSelectedValue(), "Selected Country", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_CountriesListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CntryListLabel;
    private javax.swing.JList<String> CountriesList;
    private javax.swing.JButton PCDisplay;
    private javax.swing.JPanel PCPanel;
    private javax.swing.JPanel PieChartPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

}
